export default [
  [
    {
      position: {
        x: 0,
        y: 0,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 102,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#ffffff',
      label: 'Body',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: -22,
        y: -20,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftEye',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: 22,
        y: -20,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'RightEye',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: 0,
        y: 56,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'Mouth',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: -47,
        y: 123,
      },
      size: {
        x: 68,
        y: 35,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftFoot',
      expanded: false,
      rotation: 0,
      type: 'rectangle',
    },
    {
      position: {
        x: 70,
        y: 99,
      },
      size: {
        x: 68,
        y: 35,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftFoot',
      expanded: true,
      rotation: 0,
      type: 'rectangle',
    },
  ],
  [
    {
      position: {
        x: 0,
        y: 0,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 102,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#ffffff',
      label: 'Body',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: -22,
        y: -20,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftEye',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: 22,
        y: -20,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'RightEye',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: 0,
        y: 56,
      },
      size: {
        x: 100,
        y: 100,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'Mouth',
      expanded: false,
      rotation: 0,
      type: 'circle',
    },
    {
      position: {
        x: -66,
        y: 99,
      },
      size: {
        x: 68,
        y: 35,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftFoot',
      expanded: true,
      rotation: 0,
      type: 'rectangle',
    },
    {
      position: {
        x: 47,
        y: 123,
      },
      size: {
        x: 68,
        y: 35,
      },
      radius: 10,
      strokeColor: '#000',
      fillColor: '#000',
      color: '#000',
      label: 'LeftFoot',
      expanded: true,
      rotation: 0,
      type: 'rectangle',
    },
  ],
]
